version : '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./compose_config/mosquitto:/mosquitto/config

    
  postgres :
    image : postgres:15
    container_name : postgres-db
    restart : always
    environment : 
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 1234
    ports :
      - "5432:5432"
    volumes :
      - ./init-db:/docker-entrypoint-initdb.d